env:
  - GO11MODULE=on
  - CGO_ENABLED=0
before:
  hooks:
    - go mod download
builds:
  - goos:
      - linux
    goarch:
      - amd64
    targets:
      - linux_amd64
    main: ./cmd/api/main.go
    binary: "crispy"
    gobinary: go1.16beta1

archives:
  - replacements:
      amd64: x86_64
    name_template: '{{ .ProjectName }}-{{ .Version }}.{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'

nfpms:
  - id: 1
    vendor: sber
    homepage: https://github.com/gradusp/crispy
    maintainer: sdn <pavel.fiskovich@gmail.com> # FIXME: put correct value
    description: controller part of LBOS service
    license: Apache 2.0
#    release: 2
    formats:
      - rpm
    dependencies:
      - systemd
    replacements:
      amd64: x86_64
    bindir: /usr/bin
    file_name_template: '{{ .ProjectName }}-{{ .Version }}.{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}'
    scripts:
#      preinstall: build/rpm/preinstall.sh
      postinstall: build/rpm/postinstall.sh
      preremove: build/rpm/preremove.sh
#      postremove: build/rpm/postremove.sh
    contents:
      - src: build/rpm/crispy.service
        dst: /usr/lib/systemd/system/crispy.service
      - src: build/rpm/crispy.env
        dst: /etc/default/crispy
        type: "config|noreplace"
