version: '3.9'

services:
  openapi:
    image: swaggerapi/swagger-ui
    restart: always
    ports:
      - 80:8080
    environment:
      API_KEY: "**None**"
      SWAGGER_JSON: /app/openapi.yml
      PORT: 8080
      BASE_URL: /swagger
      SWAGGER_JSON_URL: ""
      DISPLAY_OPERATION_ID: "true"
      DEEP_LINKING: "false"
      LAYOUT: "BaseLayout"
    volumes:
      - ./openapi.yml:/app/openapi.yml

  db:
    image: postgres:10-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: secret
